create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  author text not null check (char_length(author) between 1 and 24),
  content text not null check (char_length(content) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

drop policy if exists "Anyone can read chat messages" on public.messages;
create policy "Anyone can read chat messages"
on public.messages for select
to anon, authenticated
using (true);

drop policy if exists "Anyone can send chat messages" on public.messages;
create policy "Anyone can send chat messages"
on public.messages for insert
to anon, authenticated
with check (true);

create or replace function public.censor_chat_message()
returns trigger
language plpgsql
as $$
begin
  new.author := regexp_replace(
    new.author,
    '\m(anjing|asu|bangsat|bajingan|goblok|tolol|idiot|kontol|memek|ngentot|tai|fuck|shit|bitch)\M',
    '***',
    'gi'
  );
  new.content := regexp_replace(
    new.content,
    '\m(anjing|asu|bangsat|bajingan|goblok|tolol|idiot|kontol|memek|ngentot|tai|fuck|shit|bitch)\M',
    '***',
    'gi'
  );
  return new;
end;
$$;

drop trigger if exists censor_chat_message_before_insert on public.messages;
create trigger censor_chat_message_before_insert
before insert on public.messages
for each row execute function public.censor_chat_message();

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;
end
$$;
