create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  author text not null check (char_length(author) between 1 and 24),
  content text not null check (char_length(content) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

drop policy if exists "Anyone can read chat messages" on public.messages;
create policy "Anyone can read chat messages"
on public.messages for select
to anon, authenticated
using (true);

drop policy if exists "Anyone can send chat messages" on public.messages;
create policy "Anyone can send chat messages"
on public.messages for insert
to anon, authenticated
with check (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;
end
$$;
